# Generated by scripts/release/update-cask.sh in yuyudhan/simple-voice from
# packaging/homebrew/Casks/simple-voice.rb; edit the template there, not this file.
cask "simple-voice" do
  version "0.0.4"
  sha256 "cf7e47b65be7069a28a6e5a2ede0a9b1d94e0259b4aeff8101946b74e9e72e8f"

  url "https://github.com/yuyudhan/simple-voice/releases/download/v#{version}/Simple-Voice_#{version}_aarch64.zip"
  name "Simple Voice"
  desc "System-wide dictation: speak, and polished text lands in the focused app"
  homepage "https://github.com/yuyudhan/simple-voice"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "Simple Voice.app"

  # Ad-hoc signed builds are not notarized, so Gatekeeper would refuse to open the app after a
  # download. Clearing the quarantine flag is the same as approving it once in System Settings.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Simple Voice.app"]
  end

  uninstall quit: "dev.yuyudhan.simplevoice"

  zap trash: [
    "~/.simplevoice",
    "~/Library/Application Support/dev.yuyudhan.simplevoice",
    "~/Library/Caches/dev.yuyudhan.simplevoice",
    "~/Library/LaunchAgents/Simple Voice.plist",
    "~/Library/Preferences/dev.yuyudhan.simplevoice.plist",
    "~/Library/WebKit/dev.yuyudhan.simplevoice",
  ]

  caveats <<~EOS
    This build of Simple Voice is ad-hoc signed, not notarized by Apple. Homebrew cleared the
    download quarantine so it opens normally.

    macOS ties the Microphone, Accessibility and Speech Recognition permissions to the app's
    signature. After an upgrade, if dictation stops pasting or recording, open
    System Settings > Privacy & Security, remove Simple Voice from the affected list, and grant
    it again from the app's Settings > Permissions.
  EOS
end
